name: example
description: An example of `ResizableWidget`.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.2
  flutter_markdown: ^0.6.9+1
  html: ^0.15.0
  http: ^0.13.4
  resizable_widget: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0-0

flutter:
  uses-material-design: true
